export const unclaimsHanlderAddress = "";

export const unclaimsHandlerABI = [
  {
    stateMutability: "nonpayable",
    type: "constructor",
    inputs: [
      { name: "_relayerHandler", internalType: "address", type: "address" },
      { name: "_accountHandler", internalType: "address", type: "address" },
      { name: "_verifier", internalType: "address", type: "address" },
      {
        name: "_unclaimedFundClaimGas",
        internalType: "uint256",
        type: "uint256",
      },
      {
        name: "_unclaimedStateClaimGas",
        internalType: "uint256",
        type: "uint256",
      },
      {
        name: "_unclaimsExpiryDuration",
        internalType: "uint256",
        type: "uint256",
      },
      { name: "_maxFeePerGas", internalType: "uint256", type: "uint256" },
    ],
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "previousOwner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "newOwner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "OwnershipTransferred",
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "accountHandler",
    outputs: [
      { name: "", internalType: "contract AccountHandler", type: "address" },
    ],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "id", internalType: "uint256", type: "uint256" },
      {
        name: "recipientEmailAddrPointer",
        internalType: "bytes32",
        type: "bytes32",
      },
      { name: "proof", internalType: "bytes", type: "bytes" },
    ],
    name: "claimUnclaimedFund",
    outputs: [],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "id", internalType: "uint256", type: "uint256" },
      {
        name: "recipientEmailAddrPointer",
        internalType: "bytes32",
        type: "bytes32",
      },
      { name: "proof", internalType: "bytes", type: "bytes" },
    ],
    name: "claimUnclaimedState",
    outputs: [
      { name: "success", internalType: "bool", type: "bool" },
      { name: "returnData", internalType: "bytes", type: "bytes" },
    ],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [{ name: "id", internalType: "uint256", type: "uint256" }],
    name: "getUnclaimedFund",
    outputs: [
      {
        name: "",
        internalType: "struct UnclaimedFund",
        type: "tuple",
        components: [
          { name: "id", internalType: "uint256", type: "uint256" },
          { name: "emailAddrCommit", internalType: "bytes32", type: "bytes32" },
          { name: "sender", internalType: "address", type: "address" },
          { name: "tokenAddr", internalType: "address", type: "address" },
          { name: "amount", internalType: "uint256", type: "uint256" },
          { name: "expiryTime", internalType: "uint256", type: "uint256" },
        ],
      },
    ],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [{ name: "id", internalType: "uint256", type: "uint256" }],
    name: "getUnclaimedState",
    outputs: [
      {
        name: "",
        internalType: "struct UnclaimedState",
        type: "tuple",
        components: [
          { name: "id", internalType: "uint256", type: "uint256" },
          { name: "emailAddrCommit", internalType: "bytes32", type: "bytes32" },
          { name: "extensionAddr", internalType: "address", type: "address" },
          { name: "sender", internalType: "address", type: "address" },
          { name: "state", internalType: "bytes", type: "bytes" },
          { name: "expiryTime", internalType: "uint256", type: "uint256" },
        ],
      },
    ],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "maxFeePerGas",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "numUnclaimedFunds",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "numUnclaimedStates",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "owner",
    outputs: [{ name: "", internalType: "address", type: "address" }],
  },
  {
    stateMutability: "payable",
    type: "function",
    inputs: [
      { name: "emailAddrCommit", internalType: "bytes32", type: "bytes32" },
      { name: "tokenAddr", internalType: "address", type: "address" },
      { name: "amount", internalType: "uint256", type: "uint256" },
      { name: "expiryTime", internalType: "uint256", type: "uint256" },
      {
        name: "announceCommitRandomness",
        internalType: "uint256",
        type: "uint256",
      },
      { name: "announceEmailAddr", internalType: "string", type: "string" },
    ],
    name: "registerUnclaimedFund",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "sender", internalType: "address", type: "address" },
      { name: "emailAddrCommit", internalType: "bytes32", type: "bytes32" },
      { name: "tokenAddr", internalType: "address", type: "address" },
      { name: "amount", internalType: "uint256", type: "uint256" },
    ],
    name: "registerUnclaimedFundInternal",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "payable",
    type: "function",
    inputs: [
      { name: "emailAddrCommit", internalType: "bytes32", type: "bytes32" },
      { name: "extensionAddr", internalType: "address", type: "address" },
      { name: "state", internalType: "bytes", type: "bytes" },
      { name: "expiryTime", internalType: "uint256", type: "uint256" },
      {
        name: "announceCommitRandomness",
        internalType: "uint256",
        type: "uint256",
      },
      { name: "announceEmailAddr", internalType: "string", type: "string" },
    ],
    name: "registerUnclaimedState",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "extensionAddr", internalType: "address", type: "address" },
      { name: "sender", internalType: "address", type: "address" },
      {
        name: "recipientEmailAddrCommit",
        internalType: "bytes32",
        type: "bytes32",
      },
      { name: "state", internalType: "bytes", type: "bytes" },
      { name: "isInternal", internalType: "bool", type: "bool" },
    ],
    name: "registerUnclaimedStateInternal",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "relayerHandler",
    outputs: [
      { name: "", internalType: "contract RelayerHandler", type: "address" },
    ],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [{ name: "newOwner", internalType: "address", type: "address" }],
    name: "transferOwnership",
    outputs: [],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "unclaimedFundClaimGas",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    name: "unclaimedFundOfId",
    outputs: [
      { name: "id", internalType: "uint256", type: "uint256" },
      { name: "emailAddrCommit", internalType: "bytes32", type: "bytes32" },
      { name: "sender", internalType: "address", type: "address" },
      { name: "tokenAddr", internalType: "address", type: "address" },
      { name: "amount", internalType: "uint256", type: "uint256" },
      { name: "expiryTime", internalType: "uint256", type: "uint256" },
    ],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "unclaimedStateClaimGas",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    name: "unclaimedStateOfId",
    outputs: [
      { name: "id", internalType: "uint256", type: "uint256" },
      { name: "emailAddrCommit", internalType: "bytes32", type: "bytes32" },
      { name: "extensionAddr", internalType: "address", type: "address" },
      { name: "sender", internalType: "address", type: "address" },
      { name: "state", internalType: "bytes", type: "bytes" },
      { name: "expiryTime", internalType: "uint256", type: "uint256" },
    ],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "unclaimsExpiryDuration",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "verifier",
    outputs: [
      { name: "", internalType: "contract IVerifier", type: "address" },
    ],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [{ name: "id", internalType: "uint256", type: "uint256" }],
    name: "voidUnclaimedFund",
    outputs: [],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [{ name: "id", internalType: "uint256", type: "uint256" }],
    name: "voidUnclaimedState",
    outputs: [
      { name: "success", internalType: "bool", type: "bool" },
      { name: "returnData", internalType: "bytes", type: "bytes" },
    ],
  },
  { stateMutability: "payable", type: "receive" },
] as const;
